// This is a workaroung to handle tailwindcss JIT compiler.

export const GRIDS = {
    0: {
        gridSM: 'sm:grid-cols-none',
        gridMD: 'md:grid-cols-none',
        gridLG: 'lg:grid-cols-none',
        cellSM: 'sm:col-auto',
        cellMD: 'md:col-auto',
        cellLG: 'lg:col-auto',
        gapX: 'gap-x-0',
        gapY: 'gap-y-0',
    },
    1: {
        gridSM: 'sm:grid-cols-1',
        gridMD: 'md:grid-cols-1',
        gridLG: 'lg:grid-cols-1',
        cellSM: 'sm:col-span-1',
        cellMD: 'md:col-span-1',
        cellLG: 'lg:col-span-1',
        gapX: 'gap-x-1',
        gapY: 'gap-y-1',
    },
    2: {
        gridSM: 'sm:grid-cols-2',
        gridMD: 'md:grid-cols-2',
        gridLG: 'lg:grid-cols-2',
        cellSM: 'sm:col-span-2',
        cellMD: 'md:col-span-2',
        cellLG: 'lg:col-span-2',
        gapX: 'gap-x-2',
        gapY: 'gap-y-2',
    },
    3: {
        gridSM: 'sm:grid-cols-3',
        gridMD: 'md:grid-cols-3',
        gridLG: 'lg:grid-cols-3',
        cellSM: 'sm:col-span-3',
        cellMD: 'md:col-span-3',
        cellLG: 'lg:col-span-3',
        gapX: 'gap-x-3',
        gapY: 'gap-y-3',
    },
    4: {
        gridSM: 'sm:grid-cols-4',
        gridMD: 'md:grid-cols-4',
        gridLG: 'lg:grid-cols-4',
        cellSM: 'sm:col-span-4',
        cellMD: 'md:col-span-4',
        cellLG: 'lg:col-span-4',
        gapX: 'gap-x-4',
        gapY: 'gap-y-4',
    },
    5: {
        gridSM: 'sm:grid-cols-5',
        gridMD: 'md:grid-cols-5',
        gridLG: 'lg:grid-cols-5',
        cellSM: 'sm:col-span-5',
        cellMD: 'md:col-span-5',
        cellLG: 'lg:col-span-5',
        gapX: 'gap-x-5',
        gapY: 'gap-y-5',
    },
    6: {
        gridSM: 'sm:grid-cols-6',
        gridMD: 'md:grid-cols-6',
        gridLG: 'lg:grid-cols-6',
        cellSM: 'sm:col-span-6',
        cellMD: 'md:col-span-6',
        cellLG: 'lg:col-span-6',
        gapX: 'gap-x-6',
        gapY: 'gap-y-6',
    },
    7: {
        gridSM: 'sm:grid-cols-7',
        gridMD: 'md:grid-cols-7',
        gridLG: 'lg:grid-cols-7',
        cellSM: 'sm:col-span-7',
        cellMD: 'md:col-span-7',
        cellLG: 'lg:col-span-7',
        gapX: 'gap-x-7',
        gapY: 'gap-y-7',
    },
    8: {
        gridSM: 'sm:grid-cols-8',
        gridMD: 'md:grid-cols-8',
        gridLG: 'lg:grid-cols-8',
        cellSM: 'sm:col-span-8',
        cellMD: 'md:col-span-8',
        cellLG: 'lg:col-span-8',
        gapX: 'gap-x-8',
        gapY: 'gap-y-8',
    },
    9: {
        gridSM: 'sm:grid-cols-9',
        gridMD: 'md:grid-cols-9',
        gridLG: 'lg:grid-cols-9',
        cellSM: 'sm:col-span-9',
        cellMD: 'md:col-span-9',
        cellLG: 'lg:col-span-9',
        gapX: 'gap-x-9',
        gapY: 'gap-y-9',
    },
    10: {
        gridSM: 'sm:grid-cols-10',
        gridMD: 'md:grid-cols-10',
        gridLG: 'lg:grid-cols-10',
        cellSM: 'sm:col-span-10',
        cellMD: 'md:col-span-10',
        cellLG: 'lg:col-span-10',
        gapX: 'gap-x-10',
        gapY: 'gap-y-10',
    },
    11: {
        gridSM: 'sm:grid-cols-11',
        gridMD: 'md:grid-cols-11',
        gridLG: 'lg:grid-cols-11',
        cellSM: 'sm:col-span-11',
        cellMD: 'md:col-span-11',
        cellLG: 'lg:col-span-11',
        gapX: 'gap-x-11',
        gapY: 'gap-y-11',
    },
    12: {
        gridSM: 'sm:grid-cols-12',
        gridMD: 'md:grid-cols-12',
        gridLG: 'lg:grid-cols-12',
        cellSM: 'sm:col-span-12',
        cellMD: 'md:col-span-12',
        cellLG: 'lg:col-span-12',
        gapX: 'gap-x-12',
        gapY: 'gap-y-12',
    },
}

export const ALIGNMENTS = {
    start: 'justify-self-start',
    end: 'justify-self-end',
    center: 'justify-self-center',
}
