version: "3"

services:
  client:
    build:
      context: ../
      dockerfile: ops/client/Dockerfile
    ports:
      - 3000:3000
    container_name: client
    volumes:
      - ../client:/usr/src/app
