version: "3"

services:
  server:
    build:
      context: ../
      dockerfile: ops/server/Dockerfile
    ports:
      - 3333:3333
    container_name: server
    volumes:
      - ../server:/usr/src/app
  client:
    build:
      context: ../
      dockerfile: ops/client/Dockerfile
    ports:
      - 3000:3000
    container_name: client
    depends_on:
      - server
    volumes:
      - ../client:/usr/src/app
